model:
  text:
    pretrained_model: 'bert-base-uncased'
    freeze: true
  vision:
    freeze: true
  fusion_layer: 'transformer'
  hidden_dim: 768
  n_layers: 12
  attn_heads: 12
  average_top_k_layers: 3
  head_layers: 2
  dropout: 0.1
  normalize_targets: false
  ema_decay: 0.9998
  ema_end_decay: 0.9999
  ema_anneal_end_step: 300000
dataset:
  path:
    train: 'vision/dummy_data'
    test:  'vision/dummy_data'
  input_size: 224
  in_channels: 3
  interpolation: 'bicubic'
  patch_size: 16
  num_patches: 14
  num_mask_patches: 120
  max_mask_patches_per_block: 196
  min_mask_patches_per_block: 16
  imagenet_default_mean_and_std: false
train:
  epochs: 100
  batch_size: 16
  shuffle: true
  save_ckpt_freq: 20
  checkpoint_path: '../saved_models/v1/'
criterion:
  loss_beta: 2
optimizer:
  lr: 1e-4
  lr_decay: 0.5
